### PR TITLE
Made HTTPS configurable in ClientHttpHandler and fixed a bug

### PR DESCRIPTION
**Pull request by theangrydev**

### CODE REVIEW

**Comment by danielbodart** [comment]
ClientHttpHandler HTTPS support enabled in releases:

 * [Java7 1.55](https://github.com/bodar/utterlyidle/releases/tag/1.55) 
 * [Java8 2.44](https://github.com/bodar/utterlyidle/releases/tag/2.44)

Server support coming next

**Comment by danielbodart** [comment]
Okay Server HTTPS support is now available for all implementations including Undertow in V2

 * [Java7 1.57](https://github.com/bodar/utterlyidle/releases/tag/1.57) 
 * [Java8 2.47](https://github.com/bodar/utterlyidle/releases/tag/2.47)

It's done slightly differently from your patch, basically the ServerConfiguration now supports an SSLContext (which can be used by all implementations including the Client) or you can just enable HTTPS protocol and it will use the default SSLContext and default Keystore.

I've also made a convenience class called SSL which does all the tedious Java plumbing and finally the only test added was a single test in the ServerContract so now I expect all implementations to support SSL. SecureString was also added that allows erasing of password from memory.

I will probably run [SSL Labs](https://www.ssllabs.com/ssltest/) against in and remove all the broken ciphers etc as they recommend.

Thanks for taking the time to create the patch, it was used as the inspiration for my changes.

**Comment by theangrydev** [comment]
Great, will be able to start using this today. Thanks for your help!

**Comment by danielbodart** [comment]
Okay I've add an interface called ClientConfiguration, it uses the functional builder style so now you can do:

    import static com.googlecode.utterlyidle.ClientConfiguration.Builder.*;
    new ClientHttpHandler(clientConfiguration(sslContext(context)))

Instead of the million constructor arguments we had before

**Pull request closed without merging**
